version: '3.5'
services:
  elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION} # image version for both elasticsearch and kibana must be same
    image: akhilrajmailbox/elasticsearch:elasticsearch-${ELASTIC_VERSION} # image version for both elasticsearch and kibana must be same
    container_name: elasticsearch
    hostname: elasticsearch
    restart: on-failure:5
    environment:
      - CLUSTER_NAME=my-es
      - NODE_NAME=my-master
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD} # ELASTIC_PASSWORD and ELASTICSEARCH_PASSWORD must be same
      - SECURITY_ENABLE=${ELASTIC_SECURITY}
      - MONITOR_ENABLE=true
      - ES_JAVA_OPTS=-Xms8g -Xmx8g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - /DATA/DevOps/ESCluster/data:/usr/share/elasticsearch/data
      - /DATA/DevOps/ESCluster/plugins:/usr/share/elasticsearch/plugins
    networks:
      - es-network

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION} # image version for both elasticsearch and kibana must be same
    container_name: kibana
    hostname: kibana
    restart: on-failure:5
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD} # ELASTIC_PASSWORD and ELASTICSEARCH_PASSWORD must be same
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - es-network

networks:
  es-network:
    external: true
    name: devops-network